### ISSUE TITLE
no longer needed?

### ISSUE THREAD

**Issue by mvolkmann** [mxriverlynn/jasmine.async#7]
It appears that the latest version of Jasmine allows a callback function to be passed to beforeEach, it and afterEach which makes this module no longer necessary.

Perhaps the change in Jasmine was inspired by this, so thank you very much for creating it!

**Comment by searls** [comment]
If it was added, it was added at 2.0, whereas the vast majority of jasmine usage is still 1.3.x and earlier. You may have seen it added in karma or protractor (via minijasminenode), but those are also custom patches to vanilla jasmine.

**Comment by mvolkmann** [comment]
Sorry for the misinformation! I was testing using jasmine-node and forgot that it patches beforeEach, afterEach and it to support "done" callbacks.
